# ⚠️ educational only! ⚠️
# KeepSOBP - codeserver on ghactions
# MIT licensed - https://github.com/kspactions/ghactions-codeserver/blob/main/LICENSE

name: run codeserver
on: [push, workflow_dispatch]

jobs:
  codeserver:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install cloudflared
        run: |
          wget https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-amd64.tgz
          mkdir -p cfd
          tar -xvzf cloudflared-stable-linux-amd64.tgz -C cfd
          chmod -R 777 cfd

      - name: Install codeserver
        run: curl -fsSL https://code-server.dev/install.sh | sh

      - name: run codeserver
        run: nohup code-server --port 13337 --auth password --disable-telemetry &
        env:
          PASSWORD: ${{ secrets.PASSWD }}

      - name: tunnel cloudflared
        run: nohup ./cfd/cloudflared tunnel --url http://127.0.0.1:13337 &

      - name: sleep 6h
        run: sleep 6h
